import { formatPrice } from "../catalog";
import type { DealCandidate, LoadedProduct, PriceIndexRow, ProductCluster, ProductEvent, StoreConfig } from "../types";
import { EmptyState, formatRelativeTime, Icon } from "./ui";

export function IntelligencePage({ products, clusters, prices, deals }: { products: LoadedProduct[]; clusters: ProductCluster[]; prices: PriceIndexRow[]; deals: DealCandidate[] }) {
  return <main className="workspace-main"><header className="workspace-toolbar"><div><h1>Intelligence</h1><span>{products.length.toLocaleString()} tracked products · {clusters.length.toLocaleString()} clusters</span></div></header><section className="open-section"><header><h2>Favorable offers</h2><span>{deals.length} candidates</span></header>{deals.length ? <div className="table-shell"><table><thead><tr><th>Product</th><th>Source</th><th>Current</th><th>Median</th><th>Relative</th></tr></thead><tbody>{deals.slice(0, 100).map((deal) => <tr key={`${deal.storeId}:${deal.productId}`}><td><strong>{deal.name}</strong></td><td>{deal.storeId}</td><td>{formatPrice(deal.price)}</td><td>{formatPrice(deal.clusterMedianPrice)}</td><td className="positive">{Math.round((1 - deal.relativePrice) * 100)}% lower</td></tr>)}</tbody></table></div> : <EmptyState title="No favorable offers yet">More cross-source matches are needed for useful comparisons.</EmptyState>}</section><section className="open-section"><header><h2>Store price index</h2></header><div className="price-index">{prices.map((row) => <div key={row.storeId}><strong>{row.storeId}</strong><div><span style={{ width: `${Math.min(100, row.medianRelativePrice * 70)}%` }} /></div><b>{row.medianRelativePrice.toFixed(2)}×</b></div>)}</div></section><section className="open-section"><header><h2>Product clusters</h2><span>{clusters.filter((cluster) => cluster.storeIds.length > 1).length} cross-source</span></header><div className="cluster-list">{clusters.filter((cluster) => cluster.products.length > 1).slice(0, 30).map((cluster) => <article key={cluster.id}><div><strong>{cluster.label}</strong><span>{cluster.storeIds.join(", ")}</span></div><b>{cluster.products.length} matches</b><span>{formatPrice(cluster.minPrice)} – {formatPrice(cluster.maxPrice)}</span></article>)}</div></section></main>;
}

export function ActivityPage({ events }: { events: ProductEvent[] }) {
  return <main className="workspace-main"><header className="workspace-toolbar"><div><h1>Activity</h1><span>Product changes across every source</span></div></header><section className="open-section"><div className="timeline">{events.slice(-250).reverse().map((event) => <article key={event.eventId}><span className="event-dot" /><div><strong>{event.eventType.replace("product.", "")}</strong><p>{event.storeId} · {event.productId}{event.path ? ` · ${event.path}` : ""}</p></div><time>{formatRelativeTime(event.observedAt)}</time></article>)}</div></section></main>;
}

export function SourcesPage({ stores, sync, syncing }: { stores: StoreConfig[]; sync: (id?: string) => void; syncing: boolean }) {
  return <main className="workspace-main"><header className="workspace-toolbar"><div><h1>Sources</h1><span>Read-only product connections</span></div><button className="sync-button" onClick={() => sync()} disabled={syncing}><Icon name="sync" />Sync all</button></header><section className="source-list">{stores.map((store) => <article key={store.id}><div><span>{store.kind ?? "ecwid"}</span><h2>{store.name ?? store.id}</h2><p>{store.url ?? store.id}</p></div><div><strong>{store.enabled === false ? "Paused" : "Active"}</strong><span>Every {store.syncIntervalMinutes ?? 30} min</span><button onClick={() => sync(store.id)}>Sync source</button></div></article>)}</section></main>;
}

export function SettingsPage({ apiUrl, setApiUrl }: { apiUrl: string; setApiUrl: (value: string) => void }) {
  return <main className="workspace-main narrow-page"><header className="workspace-toolbar"><div><h1>Settings</h1><span>Workspace preferences and connection</span></div></header><section className="settings-section"><h2>Connection</h2><label>API URL<input value={apiUrl} onChange={(event) => setApiUrl(event.currentTarget.value)} placeholder="/api or http://localhost:3000" /></label><p>Leave blank when using the local Vite proxy.</p></section><section className="settings-section"><h2>Safety</h2><p>All external product sources are permanently read-only. Internal assistant actions are audited and reversible where supported.</p></section></main>;
}
